language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
after_success:
- openssl aes-256-cbc -K $encrypted_9af9a5772f45_key -iv $encrypted_9af9a5772f45_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
services:
- docker
deploy:
  on:
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
