name: tournament-manager 
version: git
summary: Manage Your Tournaments.
description: |
  tournament-manager is a command-line tool
  to manage tournaments with the swiss system.

grade: stable
confinement: strict

parts:
  tournament-manager:
    source: https://github.com/fabianWrede/tournament-manager
    source-type: git
    source-subdir: src/
    plugin: python
    python-version: python3
    stage-packages:
      - texlive

apps:
  tournament-manager:
    command: bin/tournament-manager
